### ISSUE TITLE
As OpenSSL command replacement: generateRequestFromData creates a different output 

### ISSUE THREAD

**Issue by ovidiugabriel** [vakata/asn1#4]
I wanted to replace the usage of the following command 
`openssl ts -query -digest 'c9369ce7fe345436e4a14e63708f166adcdccf9d' -cert -out '/tmp/1644307371OumdE5'` with  `generateRequestFromData` as follows:

```php
$my_data = "Some Data for testing";  
// sha1( "Some Data for testing") ->  'c9369ce7fe345436e4a14e63708f166adcdccf9d' 
$raw_request = Timestamp::generateRequestFromData($my_data);

```
Since the openssl command outputs the following 
(base64 and hex for better readability):
```
MDMCAQEwITAJBgUrDgMCGgUABBTJNpzn/jRUNuShTmNwjxZq3NzPnQIIYFeD/NHTXL8BAf8=

30 33 02 01 01 30 21 30 09 06 05 2b 0e 03 02 1a 05 00 
04 14 c9 36 9c e7 fe 34 54 36 e4 a1 4e 63 70 8f 16 6a 
dc dc cf 9d 02 08 60 57 83 fc d1 d3 5c bf 01 01 ff
```

The output of `generateRequestFromData` is the following:

```
MDMCAQEwITAJBgUrDgMCGgUABBTJNpzn/jRUNuShTmNwjxZq3NzPnQIIciUfawAAAAEBAQA=

30 33 02 01 01 30 21 30 09 06 05 2b 0e 03 02 1a 05 00 
04 14 c9 36 9c e7 fe 34 54 36 e4 a1 4e 63 70 8f 16 6a 
dc dc cf 9d 02 08 72 25 1f 6b 00 00 00 01 01 01 00
```

I find your library very valuable as a replacement for openssl command execution. 
Can you please tell me where I am wrong in using your API?

**Comment by ovidiugabriel** [comment]
Comparison:

MDMCAQEwITAJBgUrDgMCGgUABBTJNpzn/jRUNuShTmNwjxZq3NzPnQII **YFeD/NHTXL8BAf8=**
MDMCAQEwITAJBgUrDgMCGgUABBTJNpzn/jRUNuShTmNwjxZq3NzPnQII **ciUfawAAAAEBAQA=**

Delta is (at the end of the message):
......................................
**37** **32** 20 **32** **35** 20 **31** **66** 
20 **36** **62** 20 **30** **30** 20 **30** 
**30** 20 **30** **30** 20 **30** **31** 20 
30 31 20 30 31 20 **30** **30**

**Comment by vakata** [comment]
This is perfectly normal, as the ASN1 structure for a timestamp request includes a nonce (which is random by definition).

Here are the decoded versions of your two strings:  
https://lapo.it/asn1js/#30330201013021300906052B0E03021A05000414C9369CE7FE345436E4A14E63708F166ADCDCCF9D0208605783FCD1D35CBF0101FF  
https://lapo.it/asn1js/#30330201013021300906052B0E03021A05000414C9369CE7FE345436E4A14E63708F166ADCDCCF9D020872251F6B00000001010100

As you can see - the differences are in the nonce and the require certificate field (the last boolean). You can control this boolean using the third parameter of ```generateRequestFromData```. This option instructs the timestamp server to include or omit its certificate in the response.

Best regards,
