### ISSUE TITLE
Wrong TSQ file

### ISSUE THREAD

**Issue by gonzalo1987** [vakata/asn1#6]
Hello Vakata, sorry about this but I'm trying to use this bundle and I'm unable to make it works right, 
if I use the command 
openssl ts -query -digest 'hash' -cert -out 'destiny_file.tsq' -sha512
I get a file like this: 
![imagen](https://user-images.githubusercontent.com/7010439/107509076-37cd2f80-6ba2-11eb-87ea-2e63b8d8be9c.png)

but using this code: (I've try using nonce on/off with the same result)
```
            $tsq = TimestampRequest::generateFromHash($hash, true, false, 'sha512');
            if ($tsq) {
                file_put_contents($tsqDestination, $tsq);

                return $tsqDestination;
            }
```
my file seems like this: 
![imagen](https://user-images.githubusercontent.com/7010439/107509154-60edc000-6ba2-11eb-83e6-caa7afc17f6f.png)

I don't understand very well how the tsq/tsr works, but my timestamp authority refuse the Vakata/TSQ and it accept the OpenSSL one, could you explain if I'm doing something wrong?

Sorry if it is only my problem and is not this bundle related one. Im not enough confidence to know it. 
Thanks you very much for your patience!

**Comment by vakata** [comment]
I am afraid this can be due to a lot of reasons. Different vendors require different attributes. Keep in mind the generateFromHash method needs binary input. Please share (if possible) both tsq files and I may be able to help further.

**Comment by gonzalo1987** [comment]
Sure, my tsq files: 
https://filebin.net/2n8av68tmg3vnv2m

In both cases I've hashed with sha512 a file that contains: 
Example to tsr
asdf

```
$data = file_get_contents($filename);
$hash = hash('sha512', $data);
```

**Comment by vakata** [comment]
Use ```hash('sha512', $data, true)``` (notice the last parameter) for ```generateFromHash``` - as I said previously: "Keep in mind the generateFromHash method needs binary input".
